{{- if eq .Values.kind "Deployment" -}}
#trivy:ignore:avd-ksv-0032
#trivy:ignore:avd-ksv-0033
#trivy:ignore:avd-ksv-0034
#trivy:ignore:avd-ksv-0035
#trivy:ignore:avd-ksv-0125
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-image-swap-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-image-swap-webhook.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.create }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pod-image-swap-webhook.selectorLabels" . | nindent 6 }}
  template:
    {{- include "pod-image-swap-webhook.podTemplate" . | nindent 4 }}
{{- end }}
